/**
 * Do not edit directly
 * Generated on Thu, 11 Jan 2024 08:48:05 GMT
 */

export const colorLightContentPrimary : string;
export const colorLightContentSecondary : string;
export const colorLightContentDisabled : string;
export const colorLightContentInteractive : string;
export const colorLightContentInverseInteractive : string;
export const colorLightContentAccent : string;
export const colorLightBordersPrimary : string;
export const colorLightBordersSecondary : string;
export const colorLightBordersTertiary : string;
export const colorLightBackgroundsPrimaryA : string;
export const colorLightBackgroundsPrimaryB : string;
export const colorLightBackgroundsSecondary : string;
export const colorLightBackgroundsDisabled : string;
export const colorLightBackgroundsInteractive : string;
export const colorLightBackgroundsPressedA : string;
export const colorLightBackgroundsPressedB : string;
export const colorLightBackgroundsAccent : string;
export const colorDarkContentPrimary : string;
export const colorDarkContentSecondary : string;
export const colorDarkContentDisabled : string;
export const colorDarkContentInteractive : string;
export const colorDarkContentInverseInteractive : string;
export const colorDarkContentAccent : string;
export const colorDarkBordersPrimary : string;
export const colorDarkBordersSecondary : string;
export const colorDarkBordersTertiary : string;
export const colorDarkBackgroundsPrimaryA : string;
export const colorDarkBackgroundsPrimaryB : string;
export const colorDarkBackgroundsSecondary : string;
export const colorDarkBackgroundsDisabled : string;
export const colorDarkBackgroundsInteractive : string;
export const colorDarkBackgroundsAccent : string;
export const fontFamiliesManrope : string;
export const lineHeights0 : number;
export const lineHeights1 : number;
export const lineHeights2 : number;
export const lineHeights3 : number;
export const lineHeights4 : number;
export const lineHeights5 : number;
export const lineHeights6 : number;
export const lineHeights7 : number;
export const lineHeights8 : number;
export const fontWeightsManrope0 : string;
export const fontWeightsManrope1 : string;
export const fontWeightsManrope2 : string;
export const fontWeightsManrope3 : string;
export const fontWeightsManrope4 : string;
export const fontSizesFontSize0 : number;
export const fontSizesFontSize1 : number;
export const fontSizesFontSize2 : number;
export const fontSizesFontSize3 : number;
export const fontSizesFontSize4 : number;
export const fontSizesFontSize5 : number;
export const fontSizesFontSize6 : number;
export const letterSpacing0 : number;
export const letterSpacing1 : number;
export const letterSpacing2 : number;
export const letterSpacing3 : number;
export const typographyHeadingXxLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyHeadingXLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyHeadingLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyHeadingMedium : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyHeadingSmall : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyHeadingXSmall : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyBodyLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyBodyMedium : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyBodySmall : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyLabelLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyLabelMedium : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyLabelSmall : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyComponentButtonLarge : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const typographyComponentButtonMedium : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: number };
export const spacingXxComfortable : number;
export const spacingXComfortable : number;
export const spacingComfortable : number;
export const spacingBase : number;
export const spacingTight : number;
export const spacingXTight : number;
export const spacingXxTight : number;
export const borderRadiusCircular : number;
export const borderRadiusMedium : number;
export const borderRadiusSmall : number;
export const borderWidthCard : number;
export const borderWidthFocus : number;
export const borderWidthDefault : number;
export const opacityVeryTransparent : number;
export const opacitySemiTransparent : number;
export const opacitySlightlyTransparent : number;
export const sizingIconXLarge : number;
export const sizingIconLarge : number;
export const sizingIconMedium : number;
export const sizingIconSmall : number;
export const borderCard : { color: string, width: number };
export const borderInput : { color: string, width: number };
export const borderInputFocus : { color: string, width: number };
export const sizingIconXSmall : number;
export const sizingButtonHeightLarge : number;
export const sizingButtonHeightMedium : number;
export const sizingMinimumTappableArea : number;
export const motionDurationDuration0 : number;
export const motionDurationDuration1 : number;
export const motionDurationDuration2 : number;
export const motionDurationDuration3 : number;
export const motionDurationDuration4 : number;
export const motionDurationDuration5 : number;
export const motionDurationDuration6 : number;
export const motionDurationDuration7 : number;
export const motionEasingEntranceEffective : string;
export const motionEasingStandardEffective : string;
export const motionEasingExitEffective : string;
export const motionEasingEntranceRevealing : string;
export const motionEasingStandardRevealing : string;
export const motionEasingExitRevealing : string;
export const motionEasingStandardAttentive : string;
export const motionDelayDelay0 : number;
export const motionDelayDelay1 : number;
export const motionDelayDelay2 : number;
export const motionDelayDelay3 : number;
export const motionDelayDelay4 : number;
